#ifndef VIGENEREDECRYPTER_ERROR_CODES_H
#define VIGENEREDECRYPTER_ERROR_CODES_H

#define RET_OK                    0x0000
#define RET_MEMORY_ALLOC_ERROR    0x0001
#define RET_INVALID_PARAM         0x0002
#define RET_FILE_OPEN_ERROR       0x0003
#define RET_FILE_READ_ERROR       0x0004
#define RET_FILE_WRITE_ERROR      0x0005
#define RET_FILE_GET_SIZE_ERROR   0x0006

#define RET_KEY_LEN_UNSUPPORTED   0x0009

#endif //VIGENEREDECRYPTER_ERROR_CODES_H
